services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-bedrijfsdata
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - TZ=Europe/Amsterdam
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist/nodes:/home/node/.n8n/custom/nodes
      - ./dist/credentials:/home/node/.n8n/custom/credentials
    restart: unless-stopped

volumes:
  n8n_data:
    driver: local
